### ISSUE TITLE
[Bug] dnd5e.documents.macro.rollItem() and Item5e.use() are broken with latest release

### ISSUE THREAD

**Issue by nimish-shah** [teroparvinen/foundry-wire#56]
I recently upgraded my foundry version to 11 build 311 and in the process also upgraded dnd5e to 2.3.1 and upgraded all of my modules to their latest versions, and I found that many of the macros I was using were not functioning correctly and throwing errors.

After much troubleshooting, I found that WIRE seems to be the cause.  I deactivated all other modules, and only turned on WIRE, and I was able to still get the errors.  When I turn on all the other modules, and disable WIRE, the errors do not occur.

When I have a Item5e object, and I call the use() function on it, I get the following error:
> Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'fastForward')
> [Detected 2 packages: wire, lib-wrapper]
>     at Item5e.onItemUse (wrappers.js:23:111)
>     at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
>     at 🎁CONFIG.Item.documentClass.prototype.use#0 (libWrapper-wrapper.js:189:20)
>     at castSpell (eval at #executeScript (foundry.js:22842:16), <anonymous>:151:24)
>     at Dialog.callback (eval at #executeScript (foundry.js:22842:16), <anonymous>:267:8)
>     at Dialog.submit (foundry.js:65093:46)
>     at Dialog._onClickButton (foundry.js:65021:10)
>     at HTMLButtonElement.dispatch (jquery.min.js:2:43184)
>     at y.handle (jquery.min.js:2:41168)

If I use the dnd5e.documents.macro.rollItem(...) function (which is what happens if you drag and drop an item to your macro bar), I get the the following error:
> Uncaught (in promise) TypeError: undefined. getMacroTarget(...)?.use is not a function
> [Detected 1 package: system:dnd5e]
>     at Object.rollItem (macro.mjs:78:44)
>     at Macro.eval (eval at #executeScript (foundry.js:22842:16), <anonymous>:3:24)
>     at #executeScript (foundry.js:22846:17)
>     at Macro.execute (foundry.js:22794:35)
>     at MacroConfig._onExecute (foundry.js:75447:17)

**Comment by nimish-shah** [comment]
After trying to go back to the prior versions, it seems like the issue started occurring in v0.11.0.  It does not occur in v0.10.12.
